spring.application.name=camel-k8s
camel.vault.kubernetescm.refreshEnabled=true
camel.vault.kubernetescm.configmaps=my-config
camel.vault.kubernetes.refreshEnabled=true
camel.vault.kubernetes.secrets=my-secret
camel.main.context-reload-enabled=true